[project]
name = "mcp-expense-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "itsapexdanav", email = "bhadauriyanirmal9102005@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastmcp>=3.4.0",
]
